### ISSUE TITLE
hard coded paths

### ISSUE THREAD

**Issue by mcroxen** [BU-ISCIII/plasmidID#1]
I think there is a hard coded path that you missed, and may want to correct for the public release:

lib/draw_circos_images.sh

cdsDdbbFile="/processing_Data/bioinformatics/research/20160530_ANTIBIOTICS_PSMP_T/REFERENCES/PLASMIDS/plasmid.all.genomic.feb212017.bed"

**Comment by pedroscampoy** [comment]
This problem should be already solved in version 1.1.0.

At first, PlasmidID required a bed file for the [plasmid database] (https://github.com/BU-ISCIII/plasmidID/wiki/Plasmid-Database) annotation, which is the hard coded path it referred to. This now has been changed and plasmids from database used as scaffold are annotated after filtering. The result of this annotation is represented as grey rectangles.

Thank you for your contribution!
