### ISSUE TITLE
ERROR in Script 

### ISSUE THREAD

**Issue by amoreming** [BU-ISCIII/plasmidID#10]
**Hi i tried to use the TEST_DATA and I have some problems executing the program. 

Here there is the input and output :** 

recercangs@recercangs-MS-7B48:~$ docker run -v $PWD:$PWD -w $PWD buisciii/plasmidid plasmidID.sh -1 /home/recercangs/plasmidID/TEST_DATA/KPN_TEST_R1.fastq.gz -2 /home/recercangs/plasmidID/TEST_DATA/KPN_TEST_R2.fastq.gz -d /home/recercangs/plasmidID/TEST_DATA/plasmids_TEST_database.fasta -s /home/recercangs/contigs_KPN_TEST.fasta  

------------------
Starting plasmidID version:1.3.3
------------------

CHECKING DEPENDENCIES AND MANDATORY FILES

DEPENDENCY	              STATUS
----------	              ------
blastn                       INSTALLED 
bowtie2-build                INSTALLED 
bowtie2                      INSTALLED 
cd-hit-est                   INSTALLED 
bedtools                     INSTALLED 
prokka                       INSTALLED 
samtools                     INSTALLED 
circos                       INSTALLED 
ERROR: please, reduce the number of characters to equal or less than 37

plasmidID is a computational pipeline tha reconstruct and annotate the most likely plasmids present in one sample

** Then I tried copipasting the archives in the main directory** 

recercangs@recercangs-MS-7B48:~$ docker run -v $PWD:$PWD -w $PWD buisciii/plasmidid plasmidID.sh -1 KPN_TEST_R1.fastq.gz -2 KPN_TEST_R2.fastq.gz -d plasmids_TEST_database.fasta -s contigs_KPN_TEST.fasta  

------------------
Starting plasmidID version:1.3.3
------------------

CHECKING DEPENDENCIES AND MANDATORY FILES

DEPENDENCY	              STATUS
----------	              ------
blastn                       INSTALLED 
bowtie2-build                INSTALLED 
bowtie2                      INSTALLED 
cd-hit-est                   INSTALLED 
bedtools                     INSTALLED 
prokka                       INSTALLED 
samtools                     INSTALLED 
circos                       INSTALLED 

Default output directory is: /home/recercangs

Log will be saved in: /home/recercangs/NO_GROUP/contigs_KPN_TEST.fasta/logs/plasmidID.log

TRIMMING READS Tue Apr  2 10:50:54 UTC 2019
 Reads will be quality trimmed with a window of 4 and an average quality of 20

DEPENDENCY	              STATUS
----------	              ------
java                         INSTALLED 

---------------------------------------

ERROR in Script plasmidID.sh on or near line 465; exiting with status 1
MESSAGE:

See /home/recercangs/logs/plasmidID.log for more information. 
command: 
 quality_trim.sh -1 KPN_TEST_R1.fastq.gz -2 KPN_TEST_R2.fastq.gz -s contigs_KPN_TEST.fasta -g NO_GROUP -o /home/recercangs/NO_GROUP/contigs_KPN_TEST.fasta/trimmed -d /opt/Trimmomatic/ -T 1

---------------------------------------
 **how can I solve the problem?**

**Comment by saramonzon** [comment]
Hi! You are almost there. 
1. You have a typo in your command line you have use -s /path/to/contigs and the correct parameter is -c. (-s is used to specify the sample custom name).
2. If you want to use the trimming functionality you have to supply the trimmomatic jar file path, in this case in the docker image is located in /scif/apps/trimmomatic/Trimmomatic-0.38 (It is specified in the repository README). You can use this command:
```Bash
docker run -v $PWD:$PWD -w $PWD buisciii/plasmidid plasmidID.sh \
     -1 TEST_DATA/KPN_TEST_R1.fastq.gz  \
     -2 TEST_DATA/KPN_TEST_R2.fastq.gz \
     -d TEST_DATA/plasmids_TEST_database.fasta \
     -c TEST_DATA/contigs_KPN_TEST.fasta \
     --trimmomatic-directory /scif/apps/trimmomatic/Trimmomatic-0.38 \
     -s KPN
```
> **Note:** with -v $PWD:$PWD -w $PWD you are making your pwd accesible to the docker image, so your input files must be located in the same folder you run the docker command or in any descendant folder.

Anyway, if you only want to try the tool with the TEST_DATA, it is already quality filtered so you can skip trimming step (--no-trim). 

Actually we recommend performing the trimming and assembly step independently of plasmidID and use --no-trim flag and -c /path/to/contigs to supply your assembly. But you can totally use it if you want.

Please ask if any other problem appears!

**Comment by saramonzon** [comment]
Hi again! I have double checked and you need to skip the trimming step in order to use the **TEST_DATA** as it is already filtered, so please use : 
```Bash
docker run -v $PWD:$PWD -w $PWD buisciii/plasmidid plasmidID.sh \
     -1 TEST_DATA/KPN_TEST_R1.fastq.gz  \
     -2 TEST_DATA/KPN_TEST_R2.fastq.gz \
     -d TEST_DATA/plasmids_TEST_database.fasta \
     -c TEST_DATA/contigs_KPN_TEST.fasta \
     --no-trim \
     -s KPN
```
