### ISSUE TITLE
error reading database.filtered

### ISSUE THREAD

**Issue by Amorenomin** [BU-ISCIII/plasmidID#20]
Hi,
I tried to used the program with this command 
plasmidID -1 forward_paired.fq.gz  -2  reverse_paired.fq.gz -d 2021-11-15_plasmids.fasta -c assembly.fasta --no-trim -s prova

and appeared this error: 
 
ERROR in Script plasmidID on or near line 610; exiting with status 1
MESSAGE:

See logs/plasmidID.log for more information.
 command:mashclust.py -i kmer/database.filtered_0.95_term.fasta -d 0.5

Am I doing anything wrong?

Albert

**Comment by saramonzon** [comment]
Hi @Amorenomin , thanks for using plasmidID and sorry for the delay in the response.

I don't see any error at first sight, could you send us the full log file in logs/plasmidID.log?

Thanks!

**Comment by saramonzon** [comment]
I'll close this due to inactivity, if you keep having issues please re-open!
