### ISSUE TITLE
ERROR in Script plasmidID on or near line 612

### ISSUE THREAD

**Issue by SaraCortes-Lara** [BU-ISCIII/plasmidID#24]
Hi, I am working with plasmidID version 1.5.1 in conda.
During the mapping reads step appears the following error:

ERROR in Script plasmidID on or near line 612

To solve that, I am trying to install the new release 1.6.5 without exit.
Can you help me with this issue?

Thank you in advance.
Best regards,
Sara

**Comment by saramonzon** [comment]
Hi @SaraCortes-Lara ! Thanks for using plasmidID.
Can you send me please the full plasmidID logs, it should be inside the output folder y a folder called `logs`.
Also send me the error you get when installing with conda  so I can see if I can get what's going on. I can install plasmidID v1.6.5 in an empty conda env.
Please try:
```
conda env create -n plasmidIDv1.6.5 plasmidID
```
and send me the standard output.
Bests

**Comment by SaraCortes-Lara** [comment]
Hi Sara,

Thank you for your reply.
You can find the logs file attached.

I tryied to install the new release with your command line but appears this message: SpecNotFound: Invalid name 'plasmidID', try the format: user/package

Best regards
[plasmidID.log](https://github.com/BU-ISCIII/plasmidID/files/9452604/plasmidID.log)[](url)

**Comment by saramonzon** [comment]
Sorry Sara, I misspelled the package name, try the name in lower case:
```
conda env create -n plasmidIDv1.6.5 plasmidid
```

**Comment by saramonzon** [comment]
you have a problem with samtools version according to the log: 
```
#Executing /home/micro/Programs/miniconda3/bin/sam_to_bam.sh 


DEPENDENCY	              STATUS
----------	              ------
samtools                     [0;32mINSTALLED[0m 
Default output directory is /home/micro/Analysis/plasmidID/NO_GROUP/E1/mapping
vie 26 ago 2022 15:08:17 CEST
Converting SAM to sorted indexed BAM in E1
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

---------------------------------------

[0;31mERROR[0m in Script sam_to_bam.sh on or near line 177; exiting with status 1
MESSAGE:

Samtools view command failed. See /home/micro/Analysis/plasmidID/NO_GROUP/E1/mapping/logs for more information.
---------------------------------------
```

so you need to install the latest plasmidID version

**Comment by SaraCortes-Lara** [comment]
Yes, I tryied to install the lastest version again but the same message appears
SpecNotFound: Invalid name 'plasmidid', try the format: user/package

**Comment by saramonzon** [comment]
Do you have bioconda configured in your conda installation? 
Check this and try again the same command: https://bioconda.github.io/

**Comment by SaraCortes-Lara** [comment]
I installed the latest version with this command line:
conda create -n plasmidIDv1.6.5 plasmidid

Now appears the following error:
ERROR in Script plasmidID on or near line 610; exiting with status 1
MESSAGE:

See /home/micro/Analysis/plasmidID/logs/plasmidID.log for more information.
 command:mashclust.py -i /home/micro/Analysis/plasmidID/NO_GROUP/E1/kmer/database.filtered_0.95_term.fasta -d 0.5

You can find the log file attached.

Thank you for your patience and help
[plasmidID.log](https://github.com/BU-ISCIII/plasmidID/files/9460033/plasmidID.log)

**Comment by saramonzon** [comment]
Hi! 
That's not the complete log file right? It seems to have failed prior to that step because the error says that it can't find the input file which is created in a previous step of the pipeline: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/micro/Analysis/plasmidID/NO_GROUP/E1/kmer/database.filtered_0.95_term.fasta'
``` 
Can you send me the full log?

**Comment by SaraCortes-Lara** [comment]
Yes, this is the full log.
I am running the analysis again because some files that I need now were created with the oldest version.

I will keep you informed.
Best wishes,
Sara

**Comment by SaraCortes-Lara** [comment]
now it works !

Thank you so much ! :)
