### ISSUE TITLE
circos error and minor error

### ISSUE THREAD

**Issue by mcroxen** [BU-ISCIII/plasmidID#3]
circos throws an error as it seemingly cannot find this file (from what I can tell does not exist):

NO_GROUP/<sample>/data/<sample>.annotation.coordinates

also after lib/prokka_annotation.sh

Removing unwanted files
rm: cannot remove 'NO_GROUP/<sample>/data/<sample>.val': No such file or directory
rm: cannot remove 'NO_GROUP/<sample>/data/<sample>.gbf': No such file or directory

which appears to be removed earlier.

**Comment by mcroxen** [comment]
I should note that the sample (from -s sample) should be displayed above, but for some reason it's not showing

e.g. NO_GROUP/sample/data/sample.annotation.coordinates

**Comment by pedroscampoy** [comment]
Circos require a 'sample.annotation.coordinates' file whether user use -a flag or not. Now this has been patched and queued for better resolving.

The only reason for this file structure -NO_GROUP//data/- is that the sample name (-s SAMPLE) was not inputted. If this error persist, please, paste the command you used.

Thank you for your contribution!
