### ISSUE TITLE
Update Singularity

### ISSUE THREAD

**Issue by Nilad** [BU-ISCIII/plasmidID#7]
In your `Singularity` update this line  `    scif install /opt/plasmidid_v1.4.0_centos7.scif` to `    scif install /opt/plasmidid_v1.4.1_centos7.scif`. 

Can you add in your `README.md` just few line to how build up your image docker or singularity like for singularity with `sudo singularity build plasmidid.simg Singularity` on the git repo or download if you have a dockerhub repo or any others online repo ?

I am just start to see & test your tool, it's look very nice. Keep it up =)

**Comment by saramonzon** [comment]
Hi Nilad! Thanks for trying our tool :)
You are right there was a minor problem with the versions in the Singularity and Docker recipes. It is fix now, and you can build the image yourself with either Docker or Singularity using the recipes in the repo.
Also, there is a docker image available in Dockerhub https://hub.docker.com/r/buisciii/plasmidid/

In the [Readme](plasmidID/README.md) you can find instructions for using the image with Singularity and Docker with the test data, and also how you can build it.

If you have any problem please contact us, and we will try to help :)

**Comment by saramonzon** [comment]
Singularity and docker are being updated with no need to update version.
