### ISSUE TITLE
Unable to copy files to container 

### ISSUE THREAD

**Issue by pedroscampoy** [BU-ISCIII/plasmidID#9]
When I run:

sudo singularity build plasmidid.simg Singularity

I get:

WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df
Copying config sha256:b9a1b1f0b2baaec83946a26d7045e4028f11eccc8b0e5b3514568e56a391beb2
 1.05 KiB / 1.05 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Copying ./scif_app_recipes/* to /opt/
FATAL:   container creation failed: unable to copy files to container fs: While copying ./scif_app_recipes/* to /tmp/sbuild-141638742/fs/opt: exit status 1
FATAL:   While performing build: while running engine: exit status 255

I have initiated and update submodules: confirmed that files exist.
I have tried with several computers and I get the same error message in both.

**Comment by saramonzon** [comment]
Do you have enough permissions and/or space in /tmp? You can define this build custom Singularity environment variables to any existing path in your PC, by default it uses /tmp.
export SINGULARITY_TMPDIR=/custom/path
export SINGULARITY_LOCALCACHEDIR=/custom/path
More info in [singularity docs](https://www.sylabs.io/guides/2.6/user-guide/build_environment.html#environment-variables)
If this is not the issue, let me know. It works for me in Ubuntu 18 and Centos 6.

**Comment by saramonzon** [comment]
This is an issue with Singularity version > 3.0, now fixed in Singularity recipe in commit https://github.com/BU-ISCIII/plasmidID/commit/b7c2bfd5e45dd291b362643b13ed16ca9a33fa02

You can see the question asked in Singularity google groups [here](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/DKyS8KRmVus)
